services:

  #http://localhost:8161/admin/index.jsp
  jms:
    image: webcenter/activemq
    container_name: activeMQ
    ports:
      - "8161:8161"
      - "11111:61616"

  postgres_all:
    image: postgres:latest
    container_name: all
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=all
      - POSTGRES_PASSWORD=all
      - POSTGRES_DB=all