services:

  postgres_clients:
    image: postgres:latest
    container_name: clients
    ports:
      - "1111:5432"
    environment:
      - POSTGRES_USER=clients
      - POSTGRES_PASSWORD=clients
      - POSTGRES_DB=clients

  postgres_companies:
    image: postgres:latest
    container_name: companies
    ports:
      - "2222:5432"
    environment:
      - POSTGRES_USER=companies
      - POSTGRES_PASSWORD=companies
      - POSTGRES_DB=companies