services:

  #http://localhost:8161/admin/index.jsp
  jms:
    image: webcenter/activemq
    container_name: activeMQ
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613

  postgres_clients:
    image: postgres:latest
    container_name: clients
    ports:
      - "1111:5432"
    environment:
      - POSTGRES_USER=clients
      - POSTGRES_PASSWORD=clients
      - POSTGRES_DB=clients

  postgres_companies:
    image: postgres:latest
    container_name: companies
    ports:
      - "2222:5432"
    environment:
      - POSTGRES_USER=companies
      - POSTGRES_PASSWORD=companies
      - POSTGRES_DB=companies

  postgres_products:
    image: postgres:latest
    container_name: products
    ports:
      - "3333:5432"
    environment:
      - POSTGRES_USER=products
      - POSTGRES_PASSWORD=products
      - POSTGRES_DB=products

  postgres_orders:
    image: postgres:latest
    container_name: orders
    ports:
      - "4444:5432"
    environment:
      - POSTGRES_USER=orders
      - POSTGRES_PASSWORD=orders
      - POSTGRES_DB=orders