scrape_configs:

  # Discover Eureka services to scrape.
  - job_name: 'eureka'

    # Scrape Eureka itself to discover new services.
    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka