global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:

  # Discover Eureka services to scrape.
  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'

    # Scrape Eureka itself to discover new services.
    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka