scrape_configs:
  - job_name: 'InvoicesMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:64453', 'host.docker.internal:64443']
        labels:
          application: 'Invoices Application'